# Copyright 2023-2024 MicroEJ Corp. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be found with this software.

#################################################################

# Manually provide defines

## Include directories
-I ..\src\main\c\inc

## Source folders
..\src\main\c

## Files to ignore


### Default macros
-DWOLFSSL_SMALL_CERT_VERIFY=1
-DWOLF_CONF_MATH=1
-DWOLF_CONF_RNG=1
-DWOLF_CONF_RSA=1
-DWOLF_CONF_ECC=1
-DWOLF_CONF_SHA2_256=1
-DWOLFSSL_KEY_GEN
-DOPENSSL_EXTRA



#################################################################

# CONF0 is used to ...
# config CONF0
## core


## main


#################################################################

# CONF1 is used to ...
# config CONF1
## core


## main


